package ms.Jwellery.presistence;
// Generated Sep 29, 2018 7:40:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CustomerGoldstock generated by hbm2java
 */
public class CustomerGoldstock  implements java.io.Serializable {


     private CustomerGoldstockId id;
     private String purpose;
     private String crDb;
     private String currentBalance;
     private String stockAddedBy;
     private Date logDt;

    public CustomerGoldstock() {
    }

    public CustomerGoldstock(CustomerGoldstockId id, String purpose, String crDb, String currentBalance, String stockAddedBy, Date logDt) {
       this.id = id;
       this.purpose = purpose;
       this.crDb = crDb;
       this.currentBalance = currentBalance;
       this.stockAddedBy = stockAddedBy;
       this.logDt = logDt;
    }
   
    public CustomerGoldstockId getId() {
        return this.id;
    }
    
    public void setId(CustomerGoldstockId id) {
        this.id = id;
    }
    public String getPurpose() {
        return this.purpose;
    }
    
    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }
    public String getCrDb() {
        return this.crDb;
    }
    
    public void setCrDb(String crDb) {
        this.crDb = crDb;
    }
    public String getCurrentBalance() {
        return this.currentBalance;
    }
    
    public void setCurrentBalance(String currentBalance) {
        this.currentBalance = currentBalance;
    }
    public String getStockAddedBy() {
        return this.stockAddedBy;
    }
    
    public void setStockAddedBy(String stockAddedBy) {
        this.stockAddedBy = stockAddedBy;
    }
    public Date getLogDt() {
        return this.logDt;
    }
    
    public void setLogDt(Date logDt) {
        this.logDt = logDt;
    }




}


