package ms.Jwellery.presistence;
// Generated Sep 29, 2018 7:40:44 PM by Hibernate Tools 4.3.1



/**
 * CustomerId generated by hbm2java
 */
public class CustomerId  implements java.io.Serializable {


     private String customerId;
     private String customerGst;
     private String customerMobile;

    public CustomerId() {
    }

    public CustomerId(String customerId, String customerGst, String customerMobile) {
       this.customerId = customerId;
       this.customerGst = customerGst;
       this.customerMobile = customerMobile;
    }
   
    public String getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }
    public String getCustomerGst() {
        return this.customerGst;
    }
    
    public void setCustomerGst(String customerGst) {
        this.customerGst = customerGst;
    }
    public String getCustomerMobile() {
        return this.customerMobile;
    }
    
    public void setCustomerMobile(String customerMobile) {
        this.customerMobile = customerMobile;
    }




}


