package ms.Jwellery.presistence;
// Generated Sep 29, 2018 7:40:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private CustomerId id;
     private String customerEmail;
     private String customerName;
     private String customerAddress;
     private String customerAddedBy;
     private Date logDt;

    public Customer() {
    }

    public Customer(CustomerId id, String customerEmail, String customerName, String customerAddress, String customerAddedBy, Date logDt) {
       this.id = id;
       this.customerEmail = customerEmail;
       this.customerName = customerName;
       this.customerAddress = customerAddress;
       this.customerAddedBy = customerAddedBy;
       this.logDt = logDt;
    }
   
    public CustomerId getId() {
        return this.id;
    }
    
    public void setId(CustomerId id) {
        this.id = id;
    }
    public String getCustomerEmail() {
        return this.customerEmail;
    }
    
    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
    }
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    public String getCustomerAddress() {
        return this.customerAddress;
    }
    
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }
    public String getCustomerAddedBy() {
        return this.customerAddedBy;
    }
    
    public void setCustomerAddedBy(String customerAddedBy) {
        this.customerAddedBy = customerAddedBy;
    }
    public Date getLogDt() {
        return this.logDt;
    }
    
    public void setLogDt(Date logDt) {
        this.logDt = logDt;
    }




}


