package ms.Jwellery.presistence;
// Generated Sep 29, 2018 7:40:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LossWorkerSalary generated by hbm2java
 */
public class LossWorkerSalary  implements java.io.Serializable {


     private String txnId;
     private String workerId;
     private String slNo;
     private String purpose;
     private String creditDebit;
     private String lastUpdate;
     private String goldCurrency;
     private String currentBalance;
     private Date logDt;

    public LossWorkerSalary() {
    }

    public LossWorkerSalary(String txnId, String workerId, String slNo, String purpose, String creditDebit, String lastUpdate, String goldCurrency, String currentBalance, Date logDt) {
       this.txnId = txnId;
       this.workerId = workerId;
       this.slNo = slNo;
       this.purpose = purpose;
       this.creditDebit = creditDebit;
       this.lastUpdate = lastUpdate;
       this.goldCurrency = goldCurrency;
       this.currentBalance = currentBalance;
       this.logDt = logDt;
    }
   
    public String getTxnId() {
        return this.txnId;
    }
    
    public void setTxnId(String txnId) {
        this.txnId = txnId;
    }
    public String getWorkerId() {
        return this.workerId;
    }
    
    public void setWorkerId(String workerId) {
        this.workerId = workerId;
    }
    public String getSlNo() {
        return this.slNo;
    }
    
    public void setSlNo(String slNo) {
        this.slNo = slNo;
    }
    public String getPurpose() {
        return this.purpose;
    }
    
    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }
    public String getCreditDebit() {
        return this.creditDebit;
    }
    
    public void setCreditDebit(String creditDebit) {
        this.creditDebit = creditDebit;
    }
    public String getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(String lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public String getGoldCurrency() {
        return this.goldCurrency;
    }
    
    public void setGoldCurrency(String goldCurrency) {
        this.goldCurrency = goldCurrency;
    }
    public String getCurrentBalance() {
        return this.currentBalance;
    }
    
    public void setCurrentBalance(String currentBalance) {
        this.currentBalance = currentBalance;
    }
    public Date getLogDt() {
        return this.logDt;
    }
    
    public void setLogDt(Date logDt) {
        this.logDt = logDt;
    }




}


