package ms.Jwellery.presistence;
// Generated Sep 29, 2018 7:40:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * OrderDescription generated by hbm2java
 */
public class OrderDescription  implements java.io.Serializable {


     private String orderDivideId;
     private String orderId;
     private String orderType;
     private String orderQuantity;
     private String avgWt;
     private Date logDt;

    public OrderDescription() {
    }

    public OrderDescription(String orderDivideId, String orderId, String orderType, String orderQuantity, String avgWt, Date logDt) {
       this.orderDivideId = orderDivideId;
       this.orderId = orderId;
       this.orderType = orderType;
       this.orderQuantity = orderQuantity;
       this.avgWt = avgWt;
       this.logDt = logDt;
    }
   
    public String getOrderDivideId() {
        return this.orderDivideId;
    }
    
    public void setOrderDivideId(String orderDivideId) {
        this.orderDivideId = orderDivideId;
    }
    public String getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }
    public String getOrderType() {
        return this.orderType;
    }
    
    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }
    public String getOrderQuantity() {
        return this.orderQuantity;
    }
    
    public void setOrderQuantity(String orderQuantity) {
        this.orderQuantity = orderQuantity;
    }
    public String getAvgWt() {
        return this.avgWt;
    }
    
    public void setAvgWt(String avgWt) {
        this.avgWt = avgWt;
    }
    public Date getLogDt() {
        return this.logDt;
    }
    
    public void setLogDt(Date logDt) {
        this.logDt = logDt;
    }




}


