package ms.Jwellery.presistence;
// Generated Sep 29, 2018 7:40:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * OrderDetails generated by hbm2java
 */
public class OrderDetails  implements java.io.Serializable {


     private String orderId;
     private String customerId;
     private String salseMan;
     private String totalQuantity;
     private String orderAddedBy;
     private String orderStatus;
     private Date logDt;

    public OrderDetails() {
    }

    public OrderDetails(String orderId, String customerId, String salseMan, String totalQuantity, String orderAddedBy, String orderStatus, Date logDt) {
       this.orderId = orderId;
       this.customerId = customerId;
       this.salseMan = salseMan;
       this.totalQuantity = totalQuantity;
       this.orderAddedBy = orderAddedBy;
       this.orderStatus = orderStatus;
       this.logDt = logDt;
    }
   
    public String getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }
    public String getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }
    public String getSalseMan() {
        return this.salseMan;
    }
    
    public void setSalseMan(String salseMan) {
        this.salseMan = salseMan;
    }
    public String getTotalQuantity() {
        return this.totalQuantity;
    }
    
    public void setTotalQuantity(String totalQuantity) {
        this.totalQuantity = totalQuantity;
    }
    public String getOrderAddedBy() {
        return this.orderAddedBy;
    }
    
    public void setOrderAddedBy(String orderAddedBy) {
        this.orderAddedBy = orderAddedBy;
    }
    public String getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }
    public Date getLogDt() {
        return this.logDt;
    }
    
    public void setLogDt(Date logDt) {
        this.logDt = logDt;
    }




}


