package ms.Jwellery.presistence;
// Generated Sep 29, 2018 7:40:44 PM by Hibernate Tools 4.3.1



/**
 * UserDetailsId generated by hbm2java
 */
public class UserDetailsId  implements java.io.Serializable {


     private String userId;
     private String userAdhar;
     private String userLogin;

    public UserDetailsId() {
    }

    public UserDetailsId(String userId, String userAdhar, String userLogin) {
       this.userId = userId;
       this.userAdhar = userAdhar;
       this.userLogin = userLogin;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getUserAdhar() {
        return this.userAdhar;
    }
    
    public void setUserAdhar(String userAdhar) {
        this.userAdhar = userAdhar;
    }
    public String getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(String userLogin) {
        this.userLogin = userLogin;
    }




}


