package ms.Jwellery.presistence;
// Generated Sep 29, 2018 7:40:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * WorkerLoss generated by hbm2java
 */
public class WorkerLoss  implements java.io.Serializable {


     private WorkerLossId id;
     private String lastAssignedBy;
     private String lossPercentage;
     private Date lastUpdated;

    public WorkerLoss() {
    }

    public WorkerLoss(WorkerLossId id, String lastAssignedBy, String lossPercentage, Date lastUpdated) {
       this.id = id;
       this.lastAssignedBy = lastAssignedBy;
       this.lossPercentage = lossPercentage;
       this.lastUpdated = lastUpdated;
    }
   
    public WorkerLossId getId() {
        return this.id;
    }
    
    public void setId(WorkerLossId id) {
        this.id = id;
    }
    public String getLastAssignedBy() {
        return this.lastAssignedBy;
    }
    
    public void setLastAssignedBy(String lastAssignedBy) {
        this.lastAssignedBy = lastAssignedBy;
    }
    public String getLossPercentage() {
        return this.lossPercentage;
    }
    
    public void setLossPercentage(String lossPercentage) {
        this.lossPercentage = lossPercentage;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }




}


