package ms.Jwellery.presistence;
// Generated Sep 29, 2018 7:40:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * WorkerRegistration generated by hbm2java
 */
public class WorkerRegistration  implements java.io.Serializable {


     private WorkerRegistrationId id;
     private String workerEmail;
     private String workerName;
     private String workerAddress;
     private String workerPassword;
     private String workerMobile;
     private byte[] workerImage;
     private String imageName;
     private String workerType;
     private String forgotPassword;
     private String workerStatus;
     private String workerSalary;
     private String workerAddedBy;
     private Date logDt;

    public WorkerRegistration() {
    }

    public WorkerRegistration(WorkerRegistrationId id, String workerEmail, String workerName, String workerAddress, String workerPassword, String workerMobile, byte[] workerImage, String imageName, String workerType, String forgotPassword, String workerStatus, String workerSalary, String workerAddedBy, Date logDt) {
       this.id = id;
       this.workerEmail = workerEmail;
       this.workerName = workerName;
       this.workerAddress = workerAddress;
       this.workerPassword = workerPassword;
       this.workerMobile = workerMobile;
       this.workerImage = workerImage;
       this.imageName = imageName;
       this.workerType = workerType;
       this.forgotPassword = forgotPassword;
       this.workerStatus = workerStatus;
       this.workerSalary = workerSalary;
       this.workerAddedBy = workerAddedBy;
       this.logDt = logDt;
    }
   
    public WorkerRegistrationId getId() {
        return this.id;
    }
    
    public void setId(WorkerRegistrationId id) {
        this.id = id;
    }
    public String getWorkerEmail() {
        return this.workerEmail;
    }
    
    public void setWorkerEmail(String workerEmail) {
        this.workerEmail = workerEmail;
    }
    public String getWorkerName() {
        return this.workerName;
    }
    
    public void setWorkerName(String workerName) {
        this.workerName = workerName;
    }
    public String getWorkerAddress() {
        return this.workerAddress;
    }
    
    public void setWorkerAddress(String workerAddress) {
        this.workerAddress = workerAddress;
    }
    public String getWorkerPassword() {
        return this.workerPassword;
    }
    
    public void setWorkerPassword(String workerPassword) {
        this.workerPassword = workerPassword;
    }
    public String getWorkerMobile() {
        return this.workerMobile;
    }
    
    public void setWorkerMobile(String workerMobile) {
        this.workerMobile = workerMobile;
    }
    public byte[] getWorkerImage() {
        return this.workerImage;
    }
    
    public void setWorkerImage(byte[] workerImage) {
        this.workerImage = workerImage;
    }
    public String getImageName() {
        return this.imageName;
    }
    
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }
    public String getWorkerType() {
        return this.workerType;
    }
    
    public void setWorkerType(String workerType) {
        this.workerType = workerType;
    }
    public String getForgotPassword() {
        return this.forgotPassword;
    }
    
    public void setForgotPassword(String forgotPassword) {
        this.forgotPassword = forgotPassword;
    }
    public String getWorkerStatus() {
        return this.workerStatus;
    }
    
    public void setWorkerStatus(String workerStatus) {
        this.workerStatus = workerStatus;
    }
    public String getWorkerSalary() {
        return this.workerSalary;
    }
    
    public void setWorkerSalary(String workerSalary) {
        this.workerSalary = workerSalary;
    }
    public String getWorkerAddedBy() {
        return this.workerAddedBy;
    }
    
    public void setWorkerAddedBy(String workerAddedBy) {
        this.workerAddedBy = workerAddedBy;
    }
    public Date getLogDt() {
        return this.logDt;
    }
    
    public void setLogDt(Date logDt) {
        this.logDt = logDt;
    }




}


