package ms.Jwellery.presistence;
// Generated Sep 29, 2018 7:40:44 PM by Hibernate Tools 4.3.1



/**
 * ItemTable generated by hbm2java
 */
public class ItemTable  implements java.io.Serializable {


     private String typeId;
     private String name;
     private String type;

    public ItemTable() {
    }

    public ItemTable(String typeId, String name, String type) {
       this.typeId = typeId;
       this.name = name;
       this.type = type;
    }
   
    public String getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


