package ms.Jwellery.presistence;
// Generated Feb 8, 2018 9:01:41 PM by Hibernate Tools 4.3.1



/**
 * UserRegistration generated by hbm2java
 */
public class UserRegistration  implements java.io.Serializable {


     private UserRegistrationId id;
     private String userPassword;
     private String mobileNo;

    public UserRegistration() {
    }

    public UserRegistration(UserRegistrationId id, String userPassword, String mobileNo) {
       this.id = id;
       this.userPassword = userPassword;
       this.mobileNo = mobileNo;
    }
   
    public UserRegistrationId getId() {
        return this.id;
    }
    
    public void setId(UserRegistrationId id) {
        this.id = id;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }




}


