package ms.Jwellery.presistence;
// Generated Sep 29, 2018 7:40:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UserDetails generated by hbm2java
 */
public class UserDetails  implements java.io.Serializable {


     private UserDetailsId id;
     private String roleId;
     private String userPassword;
     private String userEmail;
     private String userName;
     private String userAddress;
     private String userMobile;
     private byte[] userImage;
     private String userImageName;
     private String forgotPassword;
     private Date logDt;

    public UserDetails() {
    }

    public UserDetails(UserDetailsId id, String roleId, String userPassword, String userEmail, String userName, String userAddress, String userMobile, byte[] userImage, String userImageName, String forgotPassword, Date logDt) {
       this.id = id;
       this.roleId = roleId;
       this.userPassword = userPassword;
       this.userEmail = userEmail;
       this.userName = userName;
       this.userAddress = userAddress;
       this.userMobile = userMobile;
       this.userImage = userImage;
       this.userImageName = userImageName;
       this.forgotPassword = forgotPassword;
       this.logDt = logDt;
    }
   
    public UserDetailsId getId() {
        return this.id;
    }
    
    public void setId(UserDetailsId id) {
        this.id = id;
    }
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserAddress() {
        return this.userAddress;
    }
    
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }
    public String getUserMobile() {
        return this.userMobile;
    }
    
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile;
    }
    public byte[] getUserImage() {
        return this.userImage;
    }
    
    public void setUserImage(byte[] userImage) {
        this.userImage = userImage;
    }
    public String getUserImageName() {
        return this.userImageName;
    }
    
    public void setUserImageName(String userImageName) {
        this.userImageName = userImageName;
    }
    public String getForgotPassword() {
        return this.forgotPassword;
    }
    
    public void setForgotPassword(String forgotPassword) {
        this.forgotPassword = forgotPassword;
    }
    public Date getLogDt() {
        return this.logDt;
    }
    
    public void setLogDt(Date logDt) {
        this.logDt = logDt;
    }




}


