package ms.Jwellery.presistence;
// Generated Feb 8, 2018 9:01:41 PM by Hibernate Tools 4.3.1



/**
 * UserRegistrationId generated by hbm2java
 */
public class UserRegistrationId  implements java.io.Serializable {


     private String emailId;
     private String userName;

    public UserRegistrationId() {
    }

    public UserRegistrationId(String emailId, String userName) {
       this.emailId = emailId;
       this.userName = userName;
    }
   
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }




}


