package ms.Jwellery.presistence;
// Generated Feb 9, 2018 4:44:59 PM by Hibernate Tools 4.3.1



/**
 * WorkerRegistrationId generated by hbm2java
 */
public class WorkerRegistrationId  implements java.io.Serializable {


     private String workerAdhar;
     private String workerId;

    public WorkerRegistrationId() {
    }

    public WorkerRegistrationId(String workerAdhar, String workerId) {
       this.workerAdhar = workerAdhar;
       this.workerId = workerId;
    }
   
    public String getWorkerAdhar() {
        return this.workerAdhar;
    }
    
    public void setWorkerAdhar(String workerAdhar) {
        this.workerAdhar = workerAdhar;
    }
    public String getWorkerId() {
        return this.workerId;
    }
    
    public void setWorkerId(String workerId) {
        this.workerId = workerId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WorkerRegistrationId) ) return false;
		 WorkerRegistrationId castOther = ( WorkerRegistrationId ) other; 
         
		 return ( (this.getWorkerAdhar()==castOther.getWorkerAdhar()) || ( this.getWorkerAdhar()!=null && castOther.getWorkerAdhar()!=null && this.getWorkerAdhar().equals(castOther.getWorkerAdhar()) ) )
 && ( (this.getWorkerId()==castOther.getWorkerId()) || ( this.getWorkerId()!=null && castOther.getWorkerId()!=null && this.getWorkerId().equals(castOther.getWorkerId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getWorkerAdhar() == null ? 0 : this.getWorkerAdhar().hashCode() );
         result = 37 * result + ( getWorkerId() == null ? 0 : this.getWorkerId().hashCode() );
         return result;
   }   


}


