package ms.Jwellery.presistence;
// Generated Feb 9, 2018 4:44:59 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;

/**
 * WorkerRegistration generated by hbm2java
 */
public class WorkerRegistration  implements java.io.Serializable {


     private WorkerRegistrationId id;
     private String workerEmail;
     private String workerName;
     private String workerAddress;
     private String workerPassword;
     private int passToken;
     private String workerMobile;
     private byte[] workerImage;
     private String imageName;
     private BigDecimal workerGold;
     private BigDecimal workerNetbal;
     private int workerStone;
     private Date logDt;

    public WorkerRegistration() {
    }

    public WorkerRegistration(WorkerRegistrationId id, String workerEmail, String workerName, String workerAddress, String workerPassword, int passToken, String workerMobile, byte[] workerImage, String imageName, BigDecimal workerGold, BigDecimal workerNetbal, int workerStone, Date logDt) {
       this.id = id;
       this.workerEmail = workerEmail;
       this.workerName = workerName;
       this.workerAddress = workerAddress;
       this.workerPassword = workerPassword;
       this.passToken = passToken;
       this.workerMobile = workerMobile;
       this.workerImage = workerImage;
       this.imageName = imageName;
       this.workerGold = workerGold;
       this.workerNetbal = workerNetbal;
       this.workerStone = workerStone;
       this.logDt = logDt;
    }
   
    public WorkerRegistrationId getId() {
        return this.id;
    }
    
    public void setId(WorkerRegistrationId id) {
        this.id = id;
    }
    public String getWorkerEmail() {
        return this.workerEmail;
    }
    
    public void setWorkerEmail(String workerEmail) {
        this.workerEmail = workerEmail;
    }
    public String getWorkerName() {
        return this.workerName;
    }
    
    public void setWorkerName(String workerName) {
        this.workerName = workerName;
    }
    public String getWorkerAddress() {
        return this.workerAddress;
    }
    
    public void setWorkerAddress(String workerAddress) {
        this.workerAddress = workerAddress;
    }
    public String getWorkerPassword() {
        return this.workerPassword;
    }
    
    public void setWorkerPassword(String workerPassword) {
        this.workerPassword = workerPassword;
    }
    public int getPassToken() {
        return this.passToken;
    }
    
    public void setPassToken(int passToken) {
        this.passToken = passToken;
    }
    public String getWorkerMobile() {
        return this.workerMobile;
    }
    
    public void setWorkerMobile(String workerMobile) {
        this.workerMobile = workerMobile;
    }
    public byte[] getWorkerImage() {
        return this.workerImage;
    }
    
    public void setWorkerImage(byte[] workerImage) {
        this.workerImage = workerImage;
    }
    public String getImageName() {
        return this.imageName;
    }
    
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }
    public BigDecimal getWorkerGold() {
        return this.workerGold;
    }
    
    public void setWorkerGold(BigDecimal workerGold) {
        this.workerGold = workerGold;
    }
    public BigDecimal getWorkerNetbal() {
        return this.workerNetbal;
    }
    
    public void setWorkerNetbal(BigDecimal workerNetbal) {
        this.workerNetbal = workerNetbal;
    }
    public int getWorkerStone() {
        return this.workerStone;
    }
    
    public void setWorkerStone(int workerStone) {
        this.workerStone = workerStone;
    }
    public Date getLogDt() {
        return this.logDt;
    }
    
    public void setLogDt(Date logDt) {
        this.logDt = logDt;
    }




}


